-- select p.name, c.name
-- from person p join company c
-- on p.company_id=c.id
-- where c.id!=5;
--
-- select c.name, count(c.name) as sum
-- from person p join company c
-- on p.company_id =c.id
-- group by c.name
-- order by sum desc limit 1;